FROM ubuntu:20.04
RUN apt-get update
RUN apt-get -y install wget
RUN apt-get install sudo
RUN apt-get install nano

# docker build -t myubuntu .
# docker run --name myubuntu -it -v "D:\Code\bash\hod:/home/data" myubuntu
# docker start -i myubuntu